### ISSUE TITLE
부스 세션 준비

### ISSUE THREAD

**Issue by seriousran** [Pseudo-Lab/9th-builder#50]

**Comment by jsshin2022** [comment]
### Action Items 
- [x] 부스 연사자 리스트 공유 (11.4) - 신진수
- [x] 부스 연사자를 위한 소통 채널 만들기 - 김찬란
- [ ] 부스 연사자를 위한 가이드라인 작성 - 부스 스태프
  - 각 부스에서 목표를 설정할 수 있도록 안내 (ex. Github Star 50개 받기 / Linkedin Post 100개 받기 / 방명록 100개 받기)
  - 부스 자료 공유 일정 정하기
- [ ] 참여자 부스 참가를 위한 방식 구체화 (ex. QR 코드) - 부스 스태프
- [x] 참여자 방명록 남기는 방식 정하기 - 부스 스태프
  - 8th PseudoCon : Padlet으로 진행했었음 ([링크](https://padlet.com/seriousran/8th-pseudocon-jd610oafwcbk8evg))
- [ ] 부스 참여자를 위한 준비물 파악 및 물품 수요 조사 - 부스 스태프
  - 노트북 & 모니터 (Hdmi 선)
  - 컨셉 부스 영상
  - (참고) 멀티탭과 콘센트는 행사 공간에 충분히 마련되어 있음

**Comment by lynnminn** [comment]
@kyeongchan92 
간단하게 체크리스트 작성했습니다 :)

### 11/8 스탭 회의 때 확인해야 할 사항
- [x] 부스 테이블 활용 가능한지
- [x] 부스 안내판 7기 때와 동일한 것 사용하는지
- [x] 부스 컨셉 영상 필요한지

### 사전 준비
- 준비물
    - [ ] 부스 테이블 : 행사 공간에서 활용 가능한지 확인 필요. 사진상 강의실처럼 보이는 곳에 테이블 있는 것은 확인함
      - 행사 공간의 테이블 활용 가능 여부에 따라 외부 업체 테이블 빌려야 할 수도 있음
    - [ ] 노트북 & 모니터 : 가져올 수 있는 인원 확인 & 요청. 부족한 모니터가 있다면 참여 인원들께 도움 요청 필요 - **이경찬**
        - 총 4 -5개 모니터 추가적으로 필요함. (찬란님이 2개 지원해주심)
    - [ ] Hdmi 선 (모니터 가져오시는 분들에게 요청드리는 게 가장 좋을 것 같음) - **이경찬**
    - [ ] 부스 안내판 - **민예린**
        - 기존에는 가짜연구소 보유 액자에 종이 출력하여 사용
        - 이번에도 동일한 방식으로 진행할지 확인 필요하며, 동일하다면 종이 출력 필요
    - [x] 멀티탭, 콘센트 : 행사 공간 제공
- [ ] 부스 연사자를 위한 가이드라인 작성 - 이경찬
    - 각 부스별 목표 공유 요청  (ex. Github Star 50개 받기 / Linkedin Post 100개 받기 / 방명록 100개 받기)
    - 부스 자료 공유 일정 가이드
    - 각자 부스를 소개할 수 있는 컨셉 영상 요청 (30초 내외)
        - 이전 수도콘에서는 부스 세션 진행 중 대형 모니터에 컨셉 부스 영상을 반복 재생함
- 참여자 부스 참가 방식 구체화
    - QR 코드를 통한 부스 방명록 작성
    - 미정 사항 : QR 코드를 통해 보여줄 app 
### 당일 준비
- 부스 테이블 세팅 (모니터 & hdmi & 부스 안내판)
- 부스 세션에 영상 재생될 수 있도록 미리 세팅

**Comment by kyeongchan92** [comment]
### 부스별 파악 정보
조사중(11.8~)

[부스 관리 엑셀시트](https://docs.google.com/spreadsheets/d/192wrzm6ba1RFsJj94IN9r1mIJrhXH9Nbp3rCxVTHnAg/edit?gid=1814730237#gid=1814730237)

### Umoh를 이용한 부스 참여 시나리오
@lynnminn @jsshin2022 우모로 부스 방명록 달기 어떻게 할지, 아래 체크사항 확인하고, 시나리오 세워서 안내하면 되지 않을까 해요!
- '포럼'탭에 포스트를 만들어 부스 설명을 쓰고 방명록을 남기면 될지?
  - <img src="https://github.com/user-attachments/assets/fc89a284-855a-4c22-aa6a-1cd107b5f430" width="350">


  - 포럼에 각 부스 소개 글(발표자 프로필 링크, 깃헙링크 등) 올리기 
  - 댓글(방명록) 달 수 있음!
- ~그룹채팅이 가능하면, 부스용 방을 만들고 입장시켜서 방명록 남기게 하면 될지?~
  - ~아님 부스별 그룹채팅방?~
  - 안되는듯
- 테이블 스탠드에 발표자의 프로필 QR코드를 인쇄하면 될지? -> 방명록 남길 수 있게 해야하는데



### 11.8(금) 회의
- 사전 회의(with 민예린님)
  - [ ] 행사장에 사용 가능한 모니터 있는지? 어떻게 확인할 수 있는지? - 없다
  - [ ] 보상 가능한 상품(?) 있는지?
  - [ ] 만약에 QR코드 방명록 페이지 만든다면, 필요 기능
    - [ ] 부스별 방명록 남기기(10자 이상)

### 테이블
의자 3개 들어갈 정도의 크기  
<img src="https://github.com/user-attachments/assets/8b51fbf4-996d-4280-a552-573ddb147e98" width="500">

### 테이블 스탠드 안내판
<img src="https://github.com/user-attachments/assets/5b632646-e015-49b6-aeb6-975885987846" width="500">

**Comment by lynnminn** [comment]
https://join.umoh.io/ko/pricing

**Comment by kyeongchan92** [comment]
우모 빨리 익히기랑 준비물 준비!

**Comment by jsshin2022** [comment]
오 의견 감사드립니다. 저도 참가자가 우모 가입이 다 되어있고 QR 코드 기반으로 입장해야 하니, 해당 포럼을 잘 활용하면 좋을 것 같아요!
제가 생각한 준비사항과 동선은 아래와 같고 부스 업데이트 된 내용 전달드립니다 :-) @kyeongchan92, @lynnminn 
- [부스 세션 준비 링크](https://docs.google.com/spreadsheets/d/192wrzm6ba1RFsJj94IN9r1mIJrhXH9Nbp3rCxVTHnAg/edit?gid=1814730237#gid=1814730237)

### 부스 준비사항
- 댓글 방식 : @kyeongchan92 경찬님 말씀주신 것처럼 진행 
  - 이미지가 잘 안올라가던데....
- 먼저 각 부스의 포럼에 진입할 수 있도록 QR코드 만들기 - 진수 & 경찬 & 예린
- 작성 가이드 같이 논의해보기 - 진수 & 경찬 & 예린
  - 부스 대표 자료(?)
  - 정량적 목표에 맞는 부스 자료 링크 달기
- 스탠드 - 후원사 포함해서 11개 정도 필요 - 진수 준비 예정
  - 회사에서 찾아보니 다 치우셔서, 오늘 주문 완료했습니다!



### 부스 동선
- 참가자가 각 부스에 오면, 부스 포럼 QR 찍도로 안내
- QR 이후, 부스 연사자는 참가자가 방명록을 먼저쓰고 부스에 대한 설명을 들을 수 있도록 가이드
- 각 부스의 정량적인 목표에 맞춰서, 참가자와 함께 즐길 수 있는 자료 설명
- 이후 방명록 참여한 사람을 취합해, 선물 교환소에서 보상 제공

**Comment by kyeongchan92** [comment]
각 부스 소개글 예시. 언뜻 보기엔 글 포맷팅이 안되는 것 같던데...!! 일단.


---

[부스 소개] 장형기 - 스페셜한 Spatial AI

- 가짜연구소 '스페셜한 Spatial AI' 스터디 모임 리뷰 및 소개
- Gaussian Belief Propagation을 이용한 SLAM 경로 최적화 및 neuromorphic AI 소개
- 작업물(or 참고자료 or 참여링크 or 깃허브 링크 or 데모)
  - Tensorentorn에서 운영하는 서비스 및 데모 체험 링크: 업데이트 예정

---

[부스 소개] 박수형 - 국가관리급 RAG
- 가짜 연구소 RAG is All You Need 팀 성과 리뷰 및 소개
- RAG 기술 발전 동향과 사용 현황에 대한 사례 공유
- 작업물(or 참고자료 or 참여링크 or 깃허브 링크 or 데모)
  - 업데이트 예정

---

[부스 소개] 이경찬 - 제주도 맛집 추천 LLM 서비스 구현기

- 한 지붕 두 가족의 맛집 추천 LLM 서비스 구현 방식 비교
- 추천시스템 + LLM 논문 리뷰 활동 홍보
- 작업물(or 참고자료 or 참여링크 or 깃허브 링크)
  - 논문 구현 & 논문 리뷰 웹사이트 : https://www.pseudorec.com/
  - 제주도 맛집 추천 LLM 서비스 1 '잘도 맛있수다' : 링크 업데이트
  - 제주도 맛집 추천 LLM 서비스 2 '탐라는 맛' : 링크 업데이트

---

[부스 소개] 김성수 - 인과추론과 실험

- 인과추론 방향론을 통한 실험 설계 및 발전 과정 공유
- 가짜연구소 인과추론학과 협력 개입 성장 경험 공유
- 작업물(or 참고자료 or 참여링크 or 깃허브 링크 or 데모)
  - 인과추론 Github 링크: 

---

[부스 소개] 심세원 - 오늘의 건강 디저트 추천 메뉴는 뭘까요?

- 건강 디저트 추천 시스템 소개 및 모델 구축 과정 공유
- '빵그리의 오븐' 서비스 소개 & 건강형 디저트 시식 이벤트
- 작업물(or 참고자료 or 참여링크 or 깃허브 링크 or 데모)
  - 플랫폼 가입 링크: 업데이트 예정

---

[부스 소개] 한수민 - Unlock AI Skills with DataCamp

- DataCamp 소개 및 가짜연구소에서 DataCamp 이용하는 방법 안내
- 작업물(or 참고자료 or 참여링크 or 깃허브 링크 or 데모)
  - 업데이트 예정

---

[부스 소개] 민예린 - 다같이 모여서 강화학습

- 가짜연구소 모여야 강화학습 팀 소개 및 5가지 연속 모임의 경험 공유
- 강화학습에 대한 소개
- 작업물(or 참고자료 or 참여링크 or 깃허브 링크 or 데모)
  - 발표 자료 PPT: 업데이트 예정

---

[부스 소개] 정우준 - Hugging Face KREW

- 가짜연구소 Hugging Face KREW 리서치팀 성과 리뷰 및 소개
- 작업물(or 참고자료 or 참여링크 or 깃허브 링크 or 데모)
  - Notion 페이지: 업데이트 예정

---

[부스 소개] 페스트캠퍼스 - Sponsor Booth

- 후원사 페스트캠퍼스 홍보
- 후원사 소개 자료: 업데이트 예정

---

[부스 소개] 콰스웨이브 - Sponsor Booth

- 후원사 콰스웨이브 홍보
- 후원사 소개 자료: 업데이트 예정

---

[부스 소개] 텔레픽스 - Sponsor Booth

- 후원사 텔레픽스 홍보
- 후원사 소개 자료: 업데이트 예정

**Comment by kyeongchan92** [comment]
# 11.13(화) 회의

## 각 부스 발표자의 프로필에 링크트리를 만들도록 하기
- 링크드인 포스트 미리 올리고, 댓글 받기
- 깃허브 디스커션을 먼저 올리고, 댓글 받기
- 링크드인 포스트/깃허브 디스커션 이슈(권장)/포럼(비권장) 편하신 곳에 달아달라고 안내하기
 
어쨌든 프로필 나누기 위주로!

## to-do
- 저랑 예린님께 커스텀 url 줄 수 있는 권한 주세요!
- 저랑 예린님께 포스트 테스트 할 수 있는 우모 페이지 권한 주세요!
- 테이블 안내판에 연사자분들의 프로필 QR을 인쇄?!(X) 아웃풋의 QR을 인쇄(O). 예린님의 경우는 깃허브
- 포스트잇은 X

**Comment by lynnminn** [comment]
@kyeongchan92 @jsshin2022 
--> 경찬님, 진수님도 링크 부탁드립니다 ㅎㅎ

**부스 방명록 링크 관련 내용 공유**
- 부스 연사자 분들께 월요일 점심까지 방명록으로 사용할 링크 요청
- 전체 취합하면 월요일 저녁까지 최대한 진수님께 전달 가능할 것으로 예상됨

[행사 준비 정보](https://docs.google.com/spreadsheets/d/192wrzm6ba1RFsJj94IN9r1mIJrhXH9Nbp3rCxVTHnAg/edit?gid=1814730237#gid=1814730237) 에 작성
